maxprice: 100000
district:
  - 4 # 4 ЦАО
  - 21 # Хамовники
  - 13 # Дорогомилово
  - 22 # Якиманка
metro:
  - 4
  - 86
  - 115
  - 118
  - 120
  - 134
  - 143
  - 151
  - 159
  - 310
  - 8
  - 12
  - 18
  - 20
  - 33
  - 46
  - 56
  - 63
  - 80
rooms: []
# empty list: show all rooms (no room filtering)
   - 1 # 1-5: number of rooms
   - 2
   - 3
   - 4
   - 5
   - 6 # 6: 6+ rooms
   - 7 # 7: free layout (свободная планировка)
   - 9 # 9: studio
street: 
   - 2306 # Украинский бульвар
   - 685 # Бережковская набержная
   - 3248 # Кутузовский
   - 2616 # наб. Тараса Шевченко
   - 1246 # Косыгина
   - 1150 # Капранова пер.
   - 1598 # Николаева ул.